-- 基金历史估值快照：仅保存公开行情，不保存用户持仓或交易信息。
create table if not exists public.fund_valuation_history (
  id bigint generated by default as identity primary key,
  fund_code varchar(6) not null check (fund_code ~ '^[0-9]{6}$'),
  fund_name text,
  trade_date date not null,
  gztime timestamptz not null,
  source text not null check (source in ('fundgz', 'sina_ds2', 'sina_ds3', 'supabase_qdii')),
  gszzl numeric(14, 8) not null,
  gsz numeric(18, 6),
  nav numeric(18, 6),
  nav_date date,
  collected_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint fund_valuation_history_code_date_source_key unique (fund_code, trade_date, source)
);

create index if not exists idx_fund_valuation_history_code_date
  on public.fund_valuation_history (fund_code, trade_date desc);

create index if not exists idx_fund_valuation_history_trade_date
  on public.fund_valuation_history (trade_date desc);

alter table public.fund_valuation_history enable row level security;

drop policy if exists "authenticated users can read fund valuation history"
  on public.fund_valuation_history;

create policy "authenticated users can read fund valuation history"
  on public.fund_valuation_history
  for select
  to authenticated
  using (true);

comment on table public.fund_valuation_history is
  'Daily public fund valuation snapshots collected after the China market close.';

comment on column public.fund_valuation_history.gszzl is
  'fundgz/supabase_qdii use percentage points; sina sources keep their original decimal ratio for frontend compatibility.';
